name: Deploy (Coolify)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy (Coolify)
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify deploy (API)
        run: |
          curl -fsSL \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_API_TOKEN_WEB_APP }}" \
            $COOLIFY_WEBHOOK_URL
        env:
          COOLIFY_WEBHOOK_URL: ${{ secrets.COOLIFY_WEBHOOK_URL }}
